import type { ReadonlyMoveModuleAbi } from '../../contracts/move/types'

export const LOCK_STAKING_MAINNET_ABI = {
  address: '0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789',
  name: 'lock_staking',
  friends: ['0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::vip'],
  exposed_functions: [
    {
      name: 'delegate',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        'u64',
        'u64',
        '0x1::string::String',
      ],
      return: [],
    },
    {
      name: 'delegate_internal',
      visibility: 'friend',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', '0x1::fungible_asset::FungibleAsset', 'u64', '0x1::string::String'],
      return: [],
    },
    {
      name: 'undelegate',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        '0x1::option::Option<u64>',
        'u64',
        '0x1::string::String',
      ],
      return: [],
    },
    {
      name: 'batch_extend',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        'vector<0x1::object::Object<0x1::fungible_asset::Metadata>>',
        'vector<0x1::option::Option<u64>>',
        'vector<u64>',
        'vector<0x1::string::String>',
        'vector<u64>',
      ],
      return: [],
    },
    {
      name: 'delegate_hook',
      visibility: 'private',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        'u64',
        '0x1::string::String',
        '0x1::bigdecimal::BigDecimal',
      ],
      return: [],
    },
    {
      name: 'extend',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        '0x1::option::Option<u64>',
        'u64',
        '0x1::string::String',
        'u64',
      ],
      return: [],
    },
    {
      name: 'get_bonded_locked_delegations',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: [
        'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::LockedDelegationResponse>',
      ],
    },
    {
      name: 'get_lock_period_limits',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [],
      return: ['u64', 'u64'],
    },
    {
      name: 'get_locked_delegations',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: [
        'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::LockedDelegationResponse>',
      ],
    },
    {
      name: 'get_staking_address',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['address'],
    },
    {
      name: 'get_total_delegation_balance',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: [
        '0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::DelegationBalanceResponse',
      ],
    },
    {
      name: 'is_registered',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['address'],
      return: ['bool'],
    },
    {
      name: 'provide_delegate',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        'u64',
        'u64',
        '0x1::option::Option<u64>',
        'u64',
        '0x1::string::String',
      ],
      return: [],
    },
    {
      name: 'redelegate',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        '0x1::option::Option<u64>',
        'u64',
        '0x1::string::String',
        'u64',
        '0x1::string::String',
      ],
      return: [],
    },
    {
      name: 'redelegate_hook',
      visibility: 'private',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        'u64',
        '0x1::string::String',
        'u64',
        '0x1::string::String',
        '0x1::option::Option<0x1::bigdecimal::BigDecimal>',
      ],
      return: [],
    },
    {
      name: 'redelegate_hook_v2',
      visibility: 'private',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        'u64',
        '0x1::string::String',
        '0x1::option::Option<0x1::bigdecimal::BigDecimal>',
        'u64',
        '0x1::string::String',
        '0x1::bigdecimal::BigDecimal',
      ],
      return: [],
    },
    {
      name: 'single_asset_provide_delegate',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        'u64',
        '0x1::option::Option<u64>',
        'u64',
        '0x1::string::String',
      ],
      return: [],
    },
    {
      name: 'stableswap_provide_delegate',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        'vector<u64>',
        '0x1::option::Option<u64>',
        'u64',
        '0x1::string::String',
      ],
      return: [],
    },
    {
      name: 'undelegate_hook',
      visibility: 'private',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        'u64',
        '0x1::string::String',
        '0x1::option::Option<0x1::bigdecimal::BigDecimal>',
      ],
      return: [],
    },
    {
      name: 'unpack_locked_delegation',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        '&0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::LockedDelegationResponse',
      ],
      return: [
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        '0x1::string::String',
        'u64',
        'u64',
      ],
    },
    {
      name: 'update_params',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        '0x1::option::Option<u64>',
        '0x1::option::Option<u64>',
        '0x1::option::Option<u64>',
      ],
      return: [],
    },
    {
      name: 'vote_gov_proposal',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'u64', 'u64', '0x1::string::String'],
      return: [],
    },
    {
      name: 'withdraw_asset',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        '0x1::option::Option<u64>',
      ],
      return: [],
    },
    {
      name: 'withdraw_asset_for_staking_account',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        '0x1::option::Option<u64>',
      ],
      return: [],
    },
    {
      name: 'withdraw_delegator_reward',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer'],
      return: [],
    },
  ],
  structs: [
    {
      name: 'ModuleStore',
      is_native: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [
        { name: 'min_lock_period', type: 'u64' },
        { name: 'max_lock_period', type: 'u64' },
        { name: 'max_delegation_slot', type: 'u64' },
      ],
    },
    {
      name: 'Coin',
      is_native: false,
      abilities: ['copy', 'drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'denom', type: '0x1::string::String' },
        { name: 'amount', type: 'u64' },
      ],
    },
    {
      name: 'Delegation',
      is_native: false,
      abilities: ['copy', 'drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'delegator_address', type: '0x1::string::String' },
        { name: 'validator_address', type: '0x1::string::String' },
        {
          name: 'shares',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::DecCoin>',
        },
      ],
    },
    {
      name: 'DelegationResponse',
      is_native: false,
      abilities: ['copy', 'drop', 'store'],
      generic_type_params: [],
      fields: [
        {
          name: 'delegation_response',
          type: '0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::DelegationResponseInner',
        },
      ],
    },
    {
      name: 'DecCoin',
      is_native: false,
      abilities: ['copy', 'drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'denom', type: '0x1::string::String' },
        { name: 'amount', type: '0x1::bigdecimal::BigDecimal' },
      ],
    },
    {
      name: 'PageResponse',
      is_native: false,
      abilities: ['copy', 'drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'next_key', type: '0x1::string::String' },
        { name: 'total', type: 'u64' },
      ],
    },
    {
      name: 'DelegationBalanceResponse',
      is_native: false,
      abilities: ['drop'],
      generic_type_params: [],
      fields: [
        { name: 'addr', type: 'address' },
        { name: 'staking_account', type: 'address' },
        {
          name: 'balance',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::Coin>',
        },
      ],
    },
    {
      name: 'DelegationKey',
      is_native: false,
      abilities: ['copy', 'drop'],
      generic_type_params: [],
      fields: [
        { name: 'metadata', type: '0x1::object::Object<0x1::fungible_asset::Metadata>' },
        { name: 'release_time', type: 'vector<u8>' },
        { name: 'validator', type: '0x1::string::String' },
      ],
    },
    {
      name: 'DelegationRequest',
      is_native: false,
      abilities: ['copy', 'drop'],
      generic_type_params: [],
      fields: [
        { name: 'validator_addr', type: '0x1::string::String' },
        { name: 'delegator_addr', type: '0x1::string::String' },
      ],
    },
    {
      name: 'DelegationResponseInner',
      is_native: false,
      abilities: ['copy', 'drop', 'store'],
      generic_type_params: [],
      fields: [
        {
          name: 'delegation',
          type: '0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::Delegation',
        },
        {
          name: 'balance',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::Coin>',
        },
      ],
    },
    {
      name: 'DepositDelegationEvent',
      is_native: false,
      is_event: true,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'staking_account', type: 'address' },
        { name: 'metadata', type: '0x1::object::Object<0x1::fungible_asset::Metadata>' },
        { name: 'release_time', type: 'u64' },
        { name: 'validator', type: '0x1::string::String' },
        { name: 'locked_share', type: '0x1::bigdecimal::BigDecimal' },
      ],
    },
    {
      name: 'LockedDelegationResponse',
      is_native: false,
      abilities: ['drop'],
      generic_type_params: [],
      fields: [
        { name: 'metadata', type: '0x1::object::Object<0x1::fungible_asset::Metadata>' },
        { name: 'validator', type: '0x1::string::String' },
        { name: 'locked_share', type: '0x1::bigdecimal::BigDecimal' },
        { name: 'amount', type: 'u64' },
        { name: 'release_time', type: 'u64' },
      ],
    },
    {
      name: 'LockedShareKey',
      is_native: false,
      abilities: ['copy', 'drop'],
      generic_type_params: [],
      fields: [
        { name: 'metadata', type: '0x1::object::Object<0x1::fungible_asset::Metadata>' },
        { name: 'validator', type: '0x1::string::String' },
      ],
    },
    {
      name: 'MsgBeginRedelegate',
      is_native: false,
      abilities: ['drop'],
      generic_type_params: [],
      fields: [
        { name: '_type_', type: '0x1::string::String' },
        { name: 'delegator_address', type: '0x1::string::String' },
        { name: 'validator_src_address', type: '0x1::string::String' },
        { name: 'validator_dst_address', type: '0x1::string::String' },
        {
          name: 'amount',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::Coin>',
        },
      ],
    },
    {
      name: 'MsgDelegate',
      is_native: false,
      abilities: ['drop'],
      generic_type_params: [],
      fields: [
        { name: '_type_', type: '0x1::string::String' },
        { name: 'delegator_address', type: '0x1::string::String' },
        { name: 'validator_address', type: '0x1::string::String' },
        {
          name: 'amount',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::Coin>',
        },
      ],
    },
    {
      name: 'MsgUndelegate',
      is_native: false,
      abilities: ['drop'],
      generic_type_params: [],
      fields: [
        { name: '_type_', type: '0x1::string::String' },
        { name: 'delegator_address', type: '0x1::string::String' },
        { name: 'validator_address', type: '0x1::string::String' },
        {
          name: 'amount',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::Coin>',
        },
      ],
    },
    {
      name: 'MsgWithdrawDelegatorReward',
      is_native: false,
      abilities: ['drop'],
      generic_type_params: [],
      fields: [
        { name: '_type_', type: '0x1::string::String' },
        { name: 'delegator_address', type: '0x1::string::String' },
        { name: 'validator_address', type: '0x1::string::String' },
      ],
    },
    {
      name: 'Redelegation',
      is_native: false,
      abilities: ['copy', 'drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'delegator_address', type: '0x1::string::String' },
        { name: 'validator_src_address', type: '0x1::string::String' },
        { name: 'validator_dst_address', type: '0x1::string::String' },
        {
          name: 'entries',
          type: '0x1::option::Option<vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::RedelegationEntry>>',
        },
      ],
    },
    {
      name: 'RedelegationEntry',
      is_native: false,
      abilities: ['copy', 'drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'creation_height', type: 'u32' },
        { name: 'completion_time', type: '0x1::string::String' },
        {
          name: 'initial_balance',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::Coin>',
        },
        {
          name: 'shares_dst',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::DecCoin>',
        },
        { name: 'unbonding_id', type: 'u32' },
      ],
    },
    {
      name: 'RedelegationEntryResponse',
      is_native: false,
      abilities: ['copy', 'drop', 'store'],
      generic_type_params: [],
      fields: [
        {
          name: 'redelegation_entry',
          type: '0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::RedelegationEntry',
        },
        {
          name: 'balance',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::Coin>',
        },
      ],
    },
    {
      name: 'RedelegationResponse',
      is_native: false,
      abilities: ['copy', 'drop', 'store'],
      generic_type_params: [],
      fields: [
        {
          name: 'redelegation',
          type: '0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::Redelegation',
        },
        {
          name: 'entries',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::RedelegationEntryResponse>',
        },
      ],
    },
    {
      name: 'RedelegationsRequest',
      is_native: false,
      abilities: ['copy', 'drop'],
      generic_type_params: [],
      fields: [
        { name: 'delegator_addr', type: '0x1::string::String' },
        { name: 'src_validator_addr', type: '0x1::string::String' },
        { name: 'dst_validator_addr', type: '0x1::string::String' },
      ],
    },
    {
      name: 'RedelegationsResponse',
      is_native: false,
      abilities: ['copy', 'drop', 'store'],
      generic_type_params: [],
      fields: [
        {
          name: 'redelegation_responses',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::RedelegationResponse>',
        },
        {
          name: 'pagination',
          type: '0x1::option::Option<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::PageResponse>',
        },
      ],
    },
    {
      name: 'StakingAccount',
      is_native: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [
        { name: 'extend_ref', type: '0x1::object::ExtendRef' },
        { name: 'last_height', type: 'u64' },
        { name: 'validators', type: '0x1::table::Table<0x1::string::String, u16>' },
        {
          name: 'delegations',
          type: '0x1::table::Table<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::DelegationKey, 0x1::bigdecimal::BigDecimal>',
        },
        {
          name: 'total_locked_shares',
          type: '0x1::table::Table<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::LockedShareKey, 0x1::bigdecimal::BigDecimal>',
        },
      ],
    },
    {
      name: 'TotalDelegationBalanceRequest',
      is_native: false,
      abilities: ['copy', 'drop'],
      generic_type_params: [],
      fields: [{ name: 'delegator_addr', type: '0x1::string::String' }],
    },
    {
      name: 'TotalDelegationBalanceRequestV2',
      is_native: false,
      abilities: ['copy', 'drop'],
      generic_type_params: [],
      fields: [
        { name: 'delegator_addr', type: '0x1::string::String' },
        { name: 'status', type: '0x1::string::String' },
      ],
    },
    {
      name: 'TotalDelegationBalanceResponse',
      is_native: false,
      abilities: ['copy', 'drop'],
      generic_type_params: [],
      fields: [
        {
          name: 'balance',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::Coin>',
        },
      ],
    },
    {
      name: 'UnbondingDelegation',
      is_native: false,
      abilities: ['copy', 'drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'delegator_address', type: '0x1::string::String' },
        { name: 'validator_address', type: '0x1::string::String' },
        {
          name: 'entries',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::UnbondingDelegationEntry>',
        },
      ],
    },
    {
      name: 'UnbondingDelegationEntry',
      is_native: false,
      abilities: ['copy', 'drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'creation_height', type: 'u64' },
        { name: 'completion_time', type: '0x1::string::String' },
        {
          name: 'initial_balance',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::Coin>',
        },
        {
          name: 'balance',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::Coin>',
        },
        { name: 'unbonding_id', type: 'u64' },
        { name: 'unbonding_on_hold_ref_count', type: 'u64' },
      ],
    },
    {
      name: 'UnbondingDelegationRequest',
      is_native: false,
      abilities: ['copy', 'drop'],
      generic_type_params: [],
      fields: [
        { name: 'delegator_addr', type: '0x1::string::String' },
        { name: 'validator_addr', type: '0x1::string::String' },
      ],
    },
    {
      name: 'UnbondingDelegationResponse',
      is_native: false,
      abilities: ['copy', 'drop', 'store'],
      generic_type_params: [],
      fields: [
        {
          name: 'unbond',
          type: '0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::lock_staking::UnbondingDelegation',
        },
      ],
    },
    {
      name: 'WithdrawDelegationEvent',
      is_native: false,
      is_event: true,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'staking_account', type: 'address' },
        { name: 'metadata', type: '0x1::object::Object<0x1::fungible_asset::Metadata>' },
        { name: 'release_time', type: 'u64' },
        { name: 'validator', type: '0x1::string::String' },
        { name: 'locked_share', type: '0x1::bigdecimal::BigDecimal' },
      ],
    },
  ],
} as const satisfies ReadonlyMoveModuleAbi
