import type { ReadonlyMoveModuleAbi } from '../../contracts/move/types'

export const VIP_TESTNET_ABI = {
  address: '0x1e90c1e45682a1b877035b8443879a0332651a8cc965e9417d5091b25906bf77',
  name: 'vip',
  friends: ['0x1e90c1e45682a1b877035b8443879a0332651a8cc965e9417d5091b25906bf77::weight_vote'],
  exposed_functions: [
    {
      name: 'initialize',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'u64', 'address', '0x1::string::String'],
      return: [],
    },
    {
      name: 'register',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        'address',
        'u64',
        'address',
        '0x1::string::String',
        '0x1::bigdecimal::BigDecimal',
        '0x1::bigdecimal::BigDecimal',
        '0x1::bigdecimal::BigDecimal',
        'u64',
      ],
      return: [],
    },
    {
      name: 'is_registered',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['u64'],
      return: ['bool'],
    },
    {
      name: 'update_params',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        '0x1::option::Option<u64>',
        '0x1::option::Option<u64>',
        '0x1::option::Option<u64>',
        '0x1::option::Option<u64>',
        '0x1::option::Option<0x1::bigdecimal::BigDecimal>',
        '0x1::option::Option<0x1::bigdecimal::BigDecimal>',
        '0x1::option::Option<0x1::bigdecimal::BigDecimal>',
        '0x1::option::Option<0x1::bigdecimal::BigDecimal>',
        '0x1::option::Option<u64>',
      ],
      return: [],
    },
    {
      name: 'update_operator_commission',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'u64', 'u64', '0x1::bigdecimal::BigDecimal'],
      return: [],
    },
    {
      name: 'update_operator_info',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        'u64',
        'u64',
        '0x1::option::Option<address>',
        '0x1::option::Option<0x1::bigdecimal::BigDecimal>',
        '0x1::option::Option<0x1::bigdecimal::BigDecimal>',
      ],
      return: [],
    },
    {
      name: 'add_tvl_snapshot',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [],
      return: [],
    },
    {
      name: 'batch_claim_operator_reward_script',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'u64', 'u64'],
      return: [],
    },
    {
      name: 'batch_claim_user_reward_script',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'u64', 'u64', 'vector<u64>', 'vector<vector<vector<u8>>>', 'vector<u64>'],
      return: [],
    },
    {
      name: 'batch_lock_stake_script',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        'u64',
        'u64',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        '0x1::option::Option<u64>',
        '0x1::string::String',
        'vector<u64>',
        'vector<u64>',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        'u64',
        '0x1::option::Option<u64>',
      ],
      return: [],
    },
    {
      name: 'batch_stableswap_lock_stake_script',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        'u64',
        'u64',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        '0x1::option::Option<u64>',
        '0x1::string::String',
        'vector<u64>',
        'vector<u64>',
        '0x1::option::Option<u64>',
      ],
      return: [],
    },
    {
      name: 'deregister',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'u64'],
      return: [],
    },
    {
      name: 'execute_challenge',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        'u64',
        'u64',
        'u64',
        '0x1::string::String',
        '0x1::string::String',
        '0x1::string::String',
        'address',
        'vector<u8>',
        'u64',
      ],
      return: [],
    },
    {
      name: 'execute_rollup_challenge',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'u64', 'u64'],
      return: [],
    },
    {
      name: 'fund_reward_script',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer'],
      return: [],
    },
    {
      name: 'get_bridge_infos',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: [
        'vector<0x1e90c1e45682a1b877035b8443879a0332651a8cc965e9417d5091b25906bf77::vip::BridgeResponse>',
      ],
    },
    {
      name: 'get_last_submitted_stage',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['u64', 'u64'],
      return: ['u64'],
    },
    {
      name: 'get_total_l2_scores',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['u64'],
      return: [
        'vector<0x1e90c1e45682a1b877035b8443879a0332651a8cc965e9417d5091b25906bf77::vip::TotalL2ScoreResponse>',
      ],
    },
    {
      name: 'get_whitelisted_bridge_ids',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [],
      return: ['vector<u64>', 'vector<u64>'],
    },
    {
      name: 'lock_stake_script',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        'u64',
        'u64',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        '0x1::option::Option<u64>',
        '0x1::string::String',
        'u64',
        'u64',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        'u64',
        '0x1::option::Option<u64>',
      ],
      return: [],
    },
    {
      name: 'submit_snapshot',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'u64', 'u64', 'u64', 'vector<u8>', 'u64'],
      return: [],
    },
    {
      name: 'update_agent',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'address', '0x1::string::String'],
      return: [],
    },
    {
      name: 'update_agent_by_chain',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'address', '0x1::string::String'],
      return: [],
    },
    {
      name: 'update_l2_score_contract',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'u64', '0x1::string::String'],
      return: [],
    },
    {
      name: 'update_operator',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'u64', 'address'],
      return: [],
    },
    {
      name: 'update_vip_weight',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'u64', '0x1::bigdecimal::BigDecimal'],
      return: [],
    },
    {
      name: 'update_vip_weights',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'vector<u64>', 'vector<0x1::bigdecimal::BigDecimal>'],
      return: [],
    },
    {
      name: 'update_vip_weights_for_friend',
      visibility: 'friend',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: ['vector<u64>', 'vector<0x1::bigdecimal::BigDecimal>'],
      return: [],
    },
  ],
  structs: [
    {
      name: 'ModuleStore',
      is_native: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [
        { name: 'stage', type: 'u64' },
        { name: 'stage_start_time', type: 'u64' },
        { name: 'stage_end_time', type: 'u64' },
        { name: 'stage_interval', type: 'u64' },
        { name: 'vesting_period', type: 'u64' },
        { name: 'minimum_lock_staking_period', type: 'u64' },
        { name: 'challenge_period', type: 'u64' },
        {
          name: 'agent_data',
          type: '0x1e90c1e45682a1b877035b8443879a0332651a8cc965e9417d5091b25906bf77::vip::AgentData',
        },
        { name: 'minimum_score_ratio', type: '0x1::bigdecimal::BigDecimal' },
        { name: 'pool_split_ratio', type: '0x1::bigdecimal::BigDecimal' },
        { name: 'maximum_tvl_ratio', type: '0x1::bigdecimal::BigDecimal' },
        { name: 'minimum_eligible_tvl', type: 'u64' },
        { name: 'maximum_weight_ratio', type: '0x1::bigdecimal::BigDecimal' },
        {
          name: 'stage_data',
          type: '0x1::table::Table<vector<u8>, 0x1e90c1e45682a1b877035b8443879a0332651a8cc965e9417d5091b25906bf77::vip::StageData>',
        },
        {
          name: 'bridges',
          type: '0x1::table::Table<0x1e90c1e45682a1b877035b8443879a0332651a8cc965e9417d5091b25906bf77::vip::BridgeInfoKey, 0x1e90c1e45682a1b877035b8443879a0332651a8cc965e9417d5091b25906bf77::vip::Bridge>',
        },
        {
          name: 'challenges',
          type: '0x1::table::Table<vector<u8>, 0x1e90c1e45682a1b877035b8443879a0332651a8cc965e9417d5091b25906bf77::vip::ExecutedChallenge>',
        },
      ],
    },
    {
      name: 'AgentData',
      is_native: false,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'agent', type: 'address' },
        { name: 'api_uri', type: '0x1::string::String' },
      ],
    },
    {
      name: 'Bridge',
      is_native: false,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'init_stage', type: 'u64' },
        { name: 'end_stage', type: 'u64' },
        { name: 'bridge_addr', type: 'address' },
        { name: 'operator_addr', type: 'address' },
        { name: 'vip_l2_score_contract', type: '0x1::string::String' },
        { name: 'vip_weight', type: '0x1::bigdecimal::BigDecimal' },
        { name: 'vm_type', type: 'u64' },
      ],
    },
    {
      name: 'BridgeInfoKey',
      is_native: false,
      abilities: ['copy', 'drop'],
      generic_type_params: [],
      fields: [
        { name: 'is_registered', type: 'bool' },
        { name: 'bridge_id', type: 'vector<u8>' },
        { name: 'version', type: 'vector<u8>' },
      ],
    },
    {
      name: 'BridgeResponse',
      is_native: false,
      abilities: ['drop'],
      generic_type_params: [],
      fields: [
        { name: 'init_stage', type: 'u64' },
        { name: 'bridge_id', type: 'u64' },
        { name: 'version', type: 'u64' },
        { name: 'bridge_addr', type: 'address' },
        { name: 'operator_addr', type: 'address' },
        { name: 'vip_l2_score_contract', type: '0x1::string::String' },
        { name: 'vip_weight', type: '0x1::bigdecimal::BigDecimal' },
        { name: 'vm_type', type: 'u64' },
      ],
    },
    {
      name: 'ExecuteChallengeEvent',
      is_native: false,
      is_event: true,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'challenge_id', type: 'u64' },
        { name: 'bridge_id', type: 'u64' },
        { name: 'version', type: 'u64' },
        { name: 'stage', type: 'u64' },
        { name: 'title', type: '0x1::string::String' },
        { name: 'summary', type: '0x1::string::String' },
        { name: 'api_uri', type: '0x1::string::String' },
        { name: 'new_agent', type: 'address' },
        { name: 'merkle_root', type: 'vector<u8>' },
      ],
    },
    {
      name: 'ExecuteRollupChallengeEvent',
      is_native: false,
      is_event: true,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'bridge_id', type: 'u64' },
        { name: 'version', type: 'u64' },
        { name: 'stage', type: 'u64' },
      ],
    },
    {
      name: 'ExecutedChallenge',
      is_native: false,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'challenge_id', type: 'u64' },
        { name: 'bridge_id', type: 'u64' },
        { name: 'version', type: 'u64' },
        { name: 'stage', type: 'u64' },
        { name: 'new_l2_total_score', type: 'u64' },
        { name: 'title', type: '0x1::string::String' },
        { name: 'summary', type: '0x1::string::String' },
        { name: 'api_uri', type: '0x1::string::String' },
        { name: 'new_agent', type: 'address' },
        { name: 'merkle_root', type: 'vector<u8>' },
      ],
    },
    {
      name: 'FundEvent',
      is_native: false,
      is_event: true,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'stage', type: 'u64' },
        { name: 'total_operator_funded_reward', type: 'u64' },
        { name: 'total_user_funded_reward', type: 'u64' },
      ],
    },
    {
      name: 'LockStakeEvent',
      is_native: false,
      is_event: true,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'account', type: 'address' },
        { name: 'bridge_id', type: 'u64' },
        { name: 'version', type: 'u64' },
        { name: 'stage', type: 'u64' },
        { name: 'amount', type: 'u64' },
      ],
    },
    {
      name: 'ReleaseTimeUpdateEvent',
      is_native: false,
      is_event: true,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [{ name: 'stage', type: 'u64' }],
    },
    {
      name: 'RewardDistributionEvent',
      is_native: false,
      is_event: true,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'stage', type: 'u64' },
        { name: 'bridge_id', type: 'u64' },
        { name: 'version', type: 'u64' },
        { name: 'user_reward_amount', type: 'u64' },
        { name: 'operator_reward_amount', type: 'u64' },
      ],
    },
    {
      name: 'Snapshot',
      is_native: false,
      abilities: ['copy', 'drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'create_time', type: 'u64' },
        { name: 'upsert_time', type: 'u64' },
        { name: 'merkle_root', type: 'vector<u8>' },
        { name: 'total_l2_score', type: 'u64' },
      ],
    },
    {
      name: 'SnapshotKey',
      is_native: false,
      abilities: ['copy', 'drop'],
      generic_type_params: [],
      fields: [
        { name: 'bridge_id', type: 'vector<u8>' },
        { name: 'version', type: 'vector<u8>' },
      ],
    },
    {
      name: 'StageAdvanceEvent',
      is_native: false,
      is_event: true,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'stage', type: 'u64' },
        { name: 'stage_start_time', type: 'u64' },
        { name: 'stage_end_time', type: 'u64' },
        { name: 'pool_split_ratio', type: '0x1::bigdecimal::BigDecimal' },
        { name: 'total_operator_funded_reward', type: 'u64' },
        { name: 'total_user_funded_reward', type: 'u64' },
        { name: 'vesting_period', type: 'u64' },
        { name: 'minimum_score_ratio', type: '0x1::bigdecimal::BigDecimal' },
      ],
    },
    {
      name: 'StageData',
      is_native: false,
      abilities: ['store'],
      generic_type_params: [],
      fields: [
        { name: 'stage_start_time', type: 'u64' },
        { name: 'stage_end_time', type: 'u64' },
        { name: 'pool_split_ratio', type: '0x1::bigdecimal::BigDecimal' },
        { name: 'total_operator_funded_reward', type: 'u64' },
        { name: 'operator_funded_rewards', type: '0x1::table::Table<u64, u64>' },
        { name: 'total_user_funded_reward', type: 'u64' },
        { name: 'user_funded_rewards', type: '0x1::table::Table<u64, u64>' },
        { name: 'vesting_period', type: 'u64' },
        { name: 'minimum_score_ratio', type: '0x1::bigdecimal::BigDecimal' },
        {
          name: 'snapshots',
          type: '0x1::table::Table<0x1e90c1e45682a1b877035b8443879a0332651a8cc965e9417d5091b25906bf77::vip::SnapshotKey, 0x1e90c1e45682a1b877035b8443879a0332651a8cc965e9417d5091b25906bf77::vip::Snapshot>',
        },
      ],
    },
    {
      name: 'SubmitSnapshotEvent',
      is_native: false,
      is_event: true,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'bridge_id', type: 'u64' },
        { name: 'version', type: 'u64' },
        { name: 'stage', type: 'u64' },
        { name: 'total_l2_score', type: 'u64' },
        { name: 'merkle_root', type: 'vector<u8>' },
        { name: 'create_time', type: 'u64' },
      ],
    },
    {
      name: 'TotalL2ScoreResponse',
      is_native: false,
      abilities: ['drop'],
      generic_type_params: [],
      fields: [
        { name: 'bridge_id', type: 'u64' },
        { name: 'version', type: 'u64' },
        { name: 'total_l2_score', type: 'u64' },
      ],
    },
    {
      name: 'UpdateScoreContractEvent',
      is_native: false,
      is_event: true,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'bridge_id', type: 'u64' },
        { name: 'version', type: 'u64' },
        { name: 'score_contract', type: '0x1::string::String' },
      ],
    },
  ],
} as const satisfies ReadonlyMoveModuleAbi
