import type { ReadonlyMoveModuleAbi } from '../../contracts/move/types'

export const WEIGHT_VOTE_ABI = {
  address: '0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789',
  name: 'weight_vote',
  friends: [],
  exposed_functions: [
    {
      name: 'get_proposal',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['u64'],
      return: [
        '0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::weight_vote::ProposalResponse',
      ],
    },
    {
      name: 'initialize',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'u64', 'u64', 'u64', 'address'],
      return: [],
    },
    {
      name: 'get_module_store',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: [
        '0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::weight_vote::ModuleStoreResponse',
      ],
    },
    {
      name: 'unpack_module_store_response',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        '&0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::weight_vote::ModuleStoreResponse',
      ],
      return: ['u64', 'u64', 'u64', 'u64', 'u64', 'address', 'u64', 'u64'],
    },
    {
      name: 'execute_proposal',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [],
      return: [],
    },
    {
      name: 'create_proposal',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [],
      return: [],
    },
    {
      name: 'vote',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'u64', 'vector<u64>', 'vector<0x1::bigdecimal::BigDecimal>'],
      return: [],
    },
    {
      name: 'get_voting_power',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['address'],
      return: ['u64'],
    },
    {
      name: 'update_params',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        '0x1::option::Option<u64>',
        '0x1::option::Option<u64>',
        '0x1::option::Option<address>',
        '0x1::option::Option<u64>',
        '0x1::option::Option<u64>',
      ],
      return: [],
    },
    {
      name: 'get_pair_multipliers',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['vector<0x1::object::Object<0x1::fungible_asset::Metadata>>'],
      return: ['vector<0x1::bigdecimal::BigDecimal>'],
    },
    {
      name: 'get_tally_infos',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['u64'],
      return: [
        'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::weight_vote::TallyResponse>',
      ],
    },
    {
      name: 'get_total_tally',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['u64'],
      return: ['u64'],
    },
    {
      name: 'get_weight_vote',
      visibility: 'public',
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ['u64', 'address'],
      return: [
        '0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::weight_vote::WeightVoteResponse',
      ],
    },
    {
      name: 'unpack_proposal_response',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        '&0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::weight_vote::ProposalResponse',
      ],
      return: ['u64', 'u64', 'bool'],
    },
    {
      name: 'unpack_tally_response',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        '&0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::weight_vote::TallyResponse',
      ],
      return: ['u64', 'u64'],
    },
    {
      name: 'unpack_weight',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        '&0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::weight_vote::Weight',
      ],
      return: ['u64', '0x1::bigdecimal::BigDecimal'],
    },
    {
      name: 'unpack_weight_vote_response',
      visibility: 'public',
      is_entry: false,
      is_view: false,
      generic_type_params: [],
      params: [
        '&0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::weight_vote::WeightVoteResponse',
      ],
      return: [
        'u64',
        'u64',
        'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::weight_vote::Weight>',
      ],
    },
    {
      name: 'update_pair_multiplier',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        '&signer',
        '0x1::object::Object<0x1::fungible_asset::Metadata>',
        '0x1::bigdecimal::BigDecimal',
      ],
      return: [],
    },
    {
      name: 'vote_with_amount',
      visibility: 'public',
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ['&signer', 'u64', 'vector<u64>', 'vector<u64>'],
      return: [],
    },
  ],
  structs: [
    {
      name: 'ProposalResponse',
      is_native: false,
      abilities: ['drop'],
      generic_type_params: [],
      fields: [
        { name: 'total_tally', type: 'u64' },
        { name: 'voting_end_time', type: 'u64' },
        { name: 'executed', type: 'bool' },
      ],
    },
    {
      name: 'ModuleStore',
      is_native: false,
      abilities: ['key'],
      generic_type_params: [],
      fields: [
        { name: 'current_cycle', type: 'u64' },
        { name: 'cycle_interval', type: 'u64' },
        { name: 'cycle_start_time', type: 'u64' },
        { name: 'cycle_end_time', type: 'u64' },
        {
          name: 'proposals',
          type: '0x1::table::Table<vector<u8>, 0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::weight_vote::Proposal>',
        },
        { name: 'voting_period', type: 'u64' },
        {
          name: 'pair_multipliers',
          type: '0x1::table::Table<0x1::object::Object<0x1::fungible_asset::Metadata>, 0x1::bigdecimal::BigDecimal>',
        },
        { name: 'core_vesting_creator', type: 'address' },
        { name: 'max_lock_period_multiplier', type: 'u64' },
        { name: 'min_lock_period_multiplier', type: 'u64' },
      ],
    },
    {
      name: 'Weight',
      is_native: false,
      abilities: ['copy', 'drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'bridge_id', type: 'u64' },
        { name: 'weight', type: '0x1::bigdecimal::BigDecimal' },
      ],
    },
    {
      name: 'ModuleStoreResponse',
      is_native: false,
      abilities: ['drop'],
      generic_type_params: [],
      fields: [
        { name: 'current_cycle', type: 'u64' },
        { name: 'cycle_interval', type: 'u64' },
        { name: 'cycle_start_time', type: 'u64' },
        { name: 'cycle_end_time', type: 'u64' },
        { name: 'voting_period', type: 'u64' },
        { name: 'core_vesting_creator', type: 'address' },
        { name: 'max_lock_period_multiplier', type: 'u64' },
        { name: 'min_lock_period_multiplier', type: 'u64' },
      ],
    },
    {
      name: 'ExecuteProposalEvent',
      is_native: false,
      is_event: true,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'cycle', type: 'u64' },
        { name: 'bridge_ids', type: 'vector<u64>' },
        { name: 'weights', type: 'vector<0x1::bigdecimal::BigDecimal>' },
      ],
    },
    {
      name: 'Proposal',
      is_native: false,
      abilities: ['store'],
      generic_type_params: [],
      fields: [
        {
          name: 'votes',
          type: '0x1::table::Table<address, 0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::weight_vote::WeightVote>',
        },
        { name: 'total_tally', type: 'u64' },
        { name: 'tallies', type: '0x1::table::Table<vector<u8>, u64>' },
        { name: 'voting_end_time', type: 'u64' },
        { name: 'executed', type: 'bool' },
      ],
    },
    {
      name: 'TallyResponse',
      is_native: false,
      abilities: ['drop'],
      generic_type_params: [],
      fields: [
        { name: 'bridge_id', type: 'u64' },
        { name: 'tally', type: 'u64' },
      ],
    },
    {
      name: 'Vote',
      is_native: false,
      abilities: ['store'],
      generic_type_params: [],
      fields: [
        { name: 'vote_option', type: 'bool' },
        { name: 'voting_power', type: 'u64' },
      ],
    },
    {
      name: 'VoteEvent',
      is_native: false,
      is_event: true,
      abilities: ['drop', 'store'],
      generic_type_params: [],
      fields: [
        { name: 'account', type: 'address' },
        { name: 'cycle', type: 'u64' },
        { name: 'max_voting_power', type: 'u64' },
        { name: 'voting_power', type: 'u64' },
        {
          name: 'weights',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::weight_vote::Weight>',
        },
      ],
    },
    {
      name: 'WeightVote',
      is_native: false,
      abilities: ['store'],
      generic_type_params: [],
      fields: [
        { name: 'max_voting_power', type: 'u64' },
        { name: 'voting_power', type: 'u64' },
        {
          name: 'weights',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::weight_vote::Weight>',
        },
      ],
    },
    {
      name: 'WeightVoteResponse',
      is_native: false,
      abilities: ['drop'],
      generic_type_params: [],
      fields: [
        { name: 'max_voting_power', type: 'u64' },
        { name: 'voting_power', type: 'u64' },
        {
          name: 'weights',
          type: 'vector<0x3a886b32a802582f2e446e74d4a24d1d7ed01adf46d2a8f65c5723887e708789::weight_vote::Weight>',
        },
      ],
    },
  ],
} as const satisfies ReadonlyMoveModuleAbi
