/**
 * EVM JSON-RPC Client
 *
 * Provides HTTP-based JSON-RPC methods for EVM chains (minievm).
 * Used for operations not supported by gRPC like transaction receipts and logs.
 */

import { httpRequest, type HttpClientConfig } from './http-client'
import { validateHeaderConflict } from './headers'
import { ContractError } from '../errors'
import type { AuthConfig, HttpRequestOptions } from './types'

// =============================================================================
// Types
// =============================================================================

/**
 * JSON-RPC request structure
 */
interface JsonRpcRequest {
  jsonrpc: '2.0'
  method: string
  params: unknown[]
  id: number
}

/**
 * JSON-RPC response structure
 */
interface JsonRpcResponse<T> {
  jsonrpc: '2.0'
  result?: T
  error?: {
    code: number
    message: string
    data?: unknown
  }
  id: number
}

/**
 * EVM log entry
 */
export interface EvmLog {
  /** Address from which this log originated */
  address: string
  /** Array of 0 to 4 32 Bytes DATA of indexed log arguments */
  topics: string[]
  /** Contains non-indexed arguments of the log */
  data: string
  /** Block number where this log was in (hex) */
  blockNumber: string
  /** Hash of the transaction this log was created from */
  transactionHash: string
  /** Index position of the transaction in the block (hex) */
  transactionIndex: string
  /** Hash of the block where this log was in */
  blockHash: string
  /** Index position in the block (hex) */
  logIndex: string
  /** true when the log was removed due to a chain reorg */
  removed: boolean
}

/**
 * Transaction receipt
 */
export interface TransactionReceipt {
  /** Hash of the transaction */
  transactionHash: string
  /** Index position of the transaction in the block (hex) */
  transactionIndex: string
  /** Hash of the block this transaction was in */
  blockHash: string
  /** Block number this transaction was in (hex) */
  blockNumber: string
  /** Address of the sender */
  from: string
  /** Address of the receiver (null for contract creation) */
  to: string | null
  /** Total gas used when this transaction was executed (hex) */
  cumulativeGasUsed: string
  /** Gas used by this specific transaction (hex) */
  gasUsed: string
  /** Contract address created if this was a contract creation, otherwise null */
  contractAddress: string | null
  /** Array of log objects generated by this transaction */
  logs: EvmLog[]
  /** Bloom filter for light clients to quickly retrieve related logs */
  logsBloom: string
  /** 1 (success) or 0 (failure) (hex) */
  status: string
  /** Post-transaction state root (pre-Byzantium) */
  root?: string
  /** Effective gas price (hex) */
  effectiveGasPrice?: string
  /** Transaction type (hex) */
  type?: string
}

/**
 * Block information
 */
export interface EvmBlock {
  /** Block number (hex) or null for pending */
  number: string | null
  /** Block hash or null for pending */
  hash: string | null
  /** Parent block hash */
  parentHash: string
  /** SHA3 of the uncles data */
  sha3Uncles: string
  /** Bloom filter for logs */
  logsBloom: string
  /** Root of the transaction trie */
  transactionsRoot: string
  /** Root of the state trie */
  stateRoot: string
  /** Root of the receipts trie */
  receiptsRoot: string
  /** Address of the miner */
  miner: string
  /** Mining difficulty (hex) */
  difficulty: string
  /** Total difficulty (hex) */
  totalDifficulty: string
  /** Extra data */
  extraData: string
  /** Block size in bytes (hex) */
  size: string
  /** Gas limit (hex) */
  gasLimit: string
  /** Gas used (hex) */
  gasUsed: string
  /** Block timestamp (hex) */
  timestamp: string
  /** Array of transaction hashes or transaction objects */
  transactions: string[] | object[]
  /** Array of uncle hashes */
  uncles: string[]
  /** Base fee per gas (hex, EIP-1559) */
  baseFeePerGas?: string
}

/**
 * Filter parameters for getLogs
 */
export interface GetLogsFilter {
  /** Block number (hex), "earliest", "latest", or "pending" */
  fromBlock?: string | number
  /** Block number (hex), "earliest", "latest", or "pending" */
  toBlock?: string | number
  /** Contract address or list of addresses */
  address?: string | string[]
  /** Array of topic filters */
  topics?: (string | string[] | null)[]
  /** Block hash (alternative to fromBlock/toBlock) */
  blockHash?: string
}

/**
 * Ethereum transaction object
 */
export interface EvmTransaction {
  hash: string
  nonce: string
  blockHash: string | null
  blockNumber: string | null
  transactionIndex: string | null
  from: string
  to: string | null
  value: string
  gas: string
  gasPrice: string
  input: string
  v: string
  r: string
  s: string
  type?: string
  maxFeePerGas?: string
  maxPriorityFeePerGas?: string
  chainId?: string
  accessList?: Array<{ address: string; storageKeys: string[] }>
  yParity?: string
}

/**
 * Options for creating an EVM RPC client
 */
export interface EvmRpcClientOptions {
  /** Request timeout in milliseconds (default: 30000) */
  timeout?: number
  /** Request timeout in milliseconds (preferred over timeout) */
  timeoutMs?: number
  /** Custom headers to include in requests */
  headers?: Record<string, string>
  /** Authentication configuration */
  auth?: AuthConfig
}

// =============================================================================
// Helper Functions
// =============================================================================

/**
 * Convert a number or bigint to 0x-prefixed hex string for JSON-RPC params.
 */
function numberToHex(value: number | bigint): string {
  return '0x' + value.toString(16)
}

/**
 * Convert a block number parameter to hex or block tag
 */
function formatBlockParam(block: string | number | undefined): string {
  if (block === undefined) return 'latest'
  if (typeof block === 'string') {
    if (block === 'latest' || block === 'earliest' || block === 'pending') {
      return block
    }
    // Already hex
    if (block.startsWith('0x')) return block
    // Number string
    return numberToHex(BigInt(block))
  }
  return numberToHex(block)
}

// =============================================================================
// EVM RPC Client
// =============================================================================

/**
 * EVM JSON-RPC client for minievm chains.
 *
 * Provides methods for querying transaction receipts, logs, and block information
 * that are not available through gRPC.
 *
 * @example
 * ```typescript
 * const rpc = createEvmRpcClient('https://jsonrpc-evm-1.anvil.initia.xyz')
 *
 * // Get transaction receipt
 * const receipt = await rpc.getTransactionReceipt(txHash)
 *
 * // Get logs
 * const logs = await rpc.getLogs({
 *   address: '0x...',
 *   fromBlock: 'latest',
 *   topics: ['0x...']
 * })
 *
 * // Get block number
 * const blockNumber = await rpc.getBlockNumber()
 * ```
 */
export class EvmRpcClient {
  private config: HttpClientConfig
  private requestId = 0

  constructor(endpoint: string, options: EvmRpcClientOptions = {}) {
    validateHeaderConflict(options.auth, options.headers, 'context')
    this.config = {
      endpoint,
      auth: options.auth,
      headers: { 'content-type': 'application/json', ...options.headers },
      timeoutMs: options.timeoutMs ?? options.timeout,
    }
  }

  /**
   * Make a JSON-RPC call
   */
  private async call<T>(
    method: string,
    params: unknown[] = [],
    requestOptions?: HttpRequestOptions
  ): Promise<T> {
    const request: JsonRpcRequest = {
      jsonrpc: '2.0',
      method,
      params,
      id: ++this.requestId,
    }

    const response = await httpRequest(
      this.config,
      '',
      { method: 'POST', body: JSON.stringify(request) },
      requestOptions
    )

    if (!response.ok) {
      throw new Error(`HTTP error: ${response.status} ${response.statusText}`)
    }

    const json = (await response.json()) as JsonRpcResponse<T>

    if (json.error) {
      // EVM revert: code 3 with hex data in error.data
      const revertData = typeof json.error.data === 'string' ? json.error.data : undefined
      throw new ContractError('evm', json.error.code, json.error.message, revertData)
    }

    return json.result as T
  }

  // ===========================================================================
  // Transaction Methods
  // ===========================================================================

  /**
   * Get transaction receipt by hash.
   *
   * @param txHash - Transaction hash (0x-prefixed)
   * @returns Transaction receipt or null if not found
   *
   * @example
   * ```typescript
   * const receipt = await rpc.getTransactionReceipt('0x...')
   * if (receipt) {
   *   console.log('Status:', receipt.status === '0x1' ? 'success' : 'failed')
   *   console.log('Gas used:', parseInt(receipt.gasUsed, 16))
   *   console.log('Logs:', receipt.logs.length)
   * }
   * ```
   */
  async getTransactionReceipt(
    txHash: string,
    options?: HttpRequestOptions
  ): Promise<TransactionReceipt | null> {
    return this.call<TransactionReceipt | null>('eth_getTransactionReceipt', [txHash], options)
  }

  // ===========================================================================
  // Log Methods
  // ===========================================================================

  /**
   * Get logs matching a filter.
   *
   * @param filter - Filter parameters
   * @returns Array of matching logs
   *
   * @example
   * ```typescript
   * // Get all Transfer events from an ERC20 contract
   * const transferTopic = '0xddf252ad...' // keccak256('Transfer(address,address,uint256)')
   * const logs = await rpc.getLogs({
   *   address: '0x...',
   *   fromBlock: 1000000,
   *   toBlock: 'latest',
   *   topics: [transferTopic]
   * })
   * ```
   */
  async getLogs(filter: GetLogsFilter, options?: HttpRequestOptions): Promise<EvmLog[]> {
    const params: Record<string, unknown> = {}

    if (filter.blockHash) {
      params.blockHash = filter.blockHash
    } else {
      if (filter.fromBlock !== undefined) {
        params.fromBlock = formatBlockParam(filter.fromBlock)
      }
      if (filter.toBlock !== undefined) {
        params.toBlock = formatBlockParam(filter.toBlock)
      }
    }

    if (filter.address) {
      params.address = filter.address
    }

    if (filter.topics) {
      params.topics = filter.topics
    }

    return this.call<EvmLog[]>('eth_getLogs', [params], options)
  }

  // ===========================================================================
  // Block Methods
  // ===========================================================================

  /**
   * Get the current block number.
   *
   * @returns Current block number
   *
   * @example
   * ```typescript
   * const blockNumber = await rpc.getBlockNumber()
   * console.log('Current block:', blockNumber)
   * ```
   */
  async getBlockNumber(options?: HttpRequestOptions): Promise<bigint> {
    const result = await this.call<string>('eth_blockNumber', [], options)
    return BigInt(result)
  }

  /**
   * Get block by number.
   *
   * @param blockNumber - Block number, "latest", "earliest", or "pending"
   * @param includeTransactions - Whether to include full transaction objects
   * @returns Block object or null if not found
   *
   * @example
   * ```typescript
   * const block = await rpc.getBlockByNumber('latest', false)
   * if (block) {
   *   console.log('Block hash:', block.hash)
   *   console.log('Tx count:', block.transactions.length)
   * }
   * ```
   */
  async getBlockByNumber(
    blockNumber: string | number | bigint,
    includeTransactions = false,
    options?: HttpRequestOptions
  ): Promise<EvmBlock | null> {
    const blockParam =
      typeof blockNumber === 'bigint' ? numberToHex(blockNumber) : formatBlockParam(blockNumber)
    return this.call<EvmBlock | null>(
      'eth_getBlockByNumber',
      [blockParam, includeTransactions],
      options
    )
  }

  /**
   * Get block by hash.
   *
   * @param blockHash - Block hash (0x-prefixed)
   * @param includeTransactions - Whether to include full transaction objects
   * @returns Block object or null if not found
   */
  async getBlockByHash(
    blockHash: string,
    includeTransactions = false,
    options?: HttpRequestOptions
  ): Promise<EvmBlock | null> {
    return this.call<EvmBlock | null>(
      'eth_getBlockByHash',
      [blockHash, includeTransactions],
      options
    )
  }

  // ===========================================================================
  // Call Methods
  // ===========================================================================

  /**
   * Execute a read-only call against a contract (eth_call).
   *
   * On revert, throws a ContractError with the raw revert data in `e.data`,
   * which can be decoded with `decodeRevertReason()`.
   *
   * @param tx - Transaction parameters (from, to, data, value)
   * @param blockNumber - Block number or tag (default: "latest")
   * @returns Hex-encoded return data
   *
   * @example
   * ```typescript
   * try {
   *   const result = await rpc.ethCall({ from: '0x...', to: '0x...', data: '0x...' })
   * } catch (e) {
   *   if (e instanceof ContractError && e.data) {
   *     const reason = decodeRevertReason(e.data, abi)
   *   }
   * }
   * ```
   */
  async ethCall(
    tx: {
      from?: string
      to: string
      data?: string
      value?: string
    },
    blockNumber: string | number = 'latest',
    options?: HttpRequestOptions
  ): Promise<string> {
    return this.call<string>('eth_call', [tx, formatBlockParam(blockNumber)], options)
  }

  // ===========================================================================
  // Transaction Sending Methods
  // ===========================================================================

  /**
   * Send a signed raw transaction.
   *
   * @param signedTx - Signed transaction as hex string (0x-prefixed)
   * @returns Transaction hash
   *
   * @example
   * ```typescript
   * const txHash = await rpc.sendRawTransaction('0x02f8...')
   * ```
   */
  async sendRawTransaction(signedTx: string, options?: HttpRequestOptions): Promise<string> {
    return this.call<string>('eth_sendRawTransaction', [signedTx], options)
  }

  /**
   * Estimate gas for a transaction.
   *
   * @param tx - Transaction parameters
   * @returns Estimated gas as bigint
   *
   * @example
   * ```typescript
   * const gas = await rpc.estimateGas({
   *   from: '0x...',
   *   to: '0x...',
   *   data: '0x...',
   * })
   * ```
   */
  async estimateGas(
    tx: {
      from: string
      to: string
      data?: string
      value?: string
    },
    options?: HttpRequestOptions
  ): Promise<bigint> {
    const result = await this.call<string>('eth_estimateGas', [tx], options)
    return BigInt(result)
  }

  // ===========================================================================
  // Chain Methods
  // ===========================================================================

  /**
   * Get the chain ID.
   *
   * @returns Chain ID as bigint
   */
  async getChainId(options?: HttpRequestOptions): Promise<bigint> {
    const result = await this.call<string>('eth_chainId', [], options)
    return BigInt(result)
  }

  /**
   * Get the current gas price.
   *
   * @returns Gas price in wei
   */
  async getGasPrice(options?: HttpRequestOptions): Promise<bigint> {
    const result = await this.call<string>('eth_gasPrice', [], options)
    return BigInt(result)
  }

  // ===========================================================================
  // Account Methods
  // ===========================================================================

  /**
   * Get the balance of an account.
   *
   * @param address - Account address (0x-prefixed)
   * @param blockNumber - Block number or tag (default: "latest")
   * @returns Balance in wei
   */
  async getBalance(
    address: string,
    blockNumber: string | number = 'latest',
    options?: HttpRequestOptions
  ): Promise<bigint> {
    const result = await this.call<string>(
      'eth_getBalance',
      [address, formatBlockParam(blockNumber)],
      options
    )
    return BigInt(result)
  }

  /**
   * Get the code at an address.
   *
   * @param address - Contract address (0x-prefixed)
   * @param blockNumber - Block number or tag (default: "latest")
   * @returns Contract bytecode or "0x" if no code
   */
  async getCode(
    address: string,
    blockNumber: string | number = 'latest',
    options?: HttpRequestOptions
  ): Promise<string> {
    return this.call<string>('eth_getCode', [address, formatBlockParam(blockNumber)], options)
  }

  /**
   * Get the transaction count (nonce) of an address.
   *
   * @param address - Account address (0x-prefixed)
   * @param blockNumber - Block number or tag (default: "latest")
   * @returns Transaction count (nonce)
   */
  async getTransactionCount(
    address: string,
    blockNumber: string | number = 'latest',
    options?: HttpRequestOptions
  ): Promise<bigint> {
    const result = await this.call<string>(
      'eth_getTransactionCount',
      [address, formatBlockParam(blockNumber)],
      options
    )
    return BigInt(result)
  }

  /**
   * Get transaction by hash.
   *
   * @param hash - Transaction hash (0x-prefixed)
   * @returns Transaction object or null if not found
   */
  async getTransactionByHash(
    hash: string,
    options?: HttpRequestOptions
  ): Promise<EvmTransaction | null> {
    return this.call<EvmTransaction | null>('eth_getTransactionByHash', [hash], options)
  }

  /**
   * Get storage value at a given position.
   *
   * @param address - Contract address (0x-prefixed)
   * @param position - Storage position (0x-prefixed hex)
   * @param blockNumber - Block number or tag (default: "latest")
   * @returns Storage value as hex string
   */
  async getStorageAt(
    address: string,
    position: string,
    blockNumber: string | number = 'latest',
    options?: HttpRequestOptions
  ): Promise<string> {
    return this.call<string>(
      'eth_getStorageAt',
      [address, position, formatBlockParam(blockNumber)],
      options
    )
  }
}

// =============================================================================
// Factory Function
// =============================================================================

/**
 * Create an EVM JSON-RPC client.
 *
 * @param endpoint - JSON-RPC endpoint URL
 * @param options - Client options
 * @returns EVM RPC client instance
 *
 * @example
 * ```typescript
 * import { createEvmRpcClient } from 'initia.js'
 *
 * const rpc = createEvmRpcClient('https://jsonrpc-evm-1.anvil.initia.xyz')
 *
 * // Get transaction receipt with decoded logs
 * const receipt = await rpc.getTransactionReceipt(txHash)
 * ```
 */
export function createEvmRpcClient(endpoint: string, options?: EvmRpcClientOptions): EvmRpcClient {
  return new EvmRpcClient(endpoint, options)
}
